#------------------------------------------------------------
# common
#------------------------------------------------------------

pg: &pg
  adapter:  postgresql
  host:     localhost
  encoding: utf8

#------------------------------------------------------------
# environments
#------------------------------------------------------------

development:
  <<: *pg
  database: foodtruckrodeo_development


test: &test
  <<: *pg
  database: foodtruckrodeo_test


production:
  <<: *pg
  database: foodtruckrodeo_production
